name: Update Meetup Date

on:
  schedule:
    - cron: '0 14 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout gemsheffield.com repo
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install bs4

      - name: Update meetup date
        run: python ./.github/update-meetup-date.py

      - name: Save new meetup date
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "[AUTO] Updated meetup date")

      - name: Push new commit
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
